# Site settings
title: Brent Gaither
email: brent.w.gaither@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brent Gaither. This is my personal site for bioinformatics and other
  cool things I learn about. 
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  brentgaither

# Build settings
markdown: kramdown
